### PR TITLE
could you approve this fix for 10.14.5

### PR DESCRIPTION
**Pull request by feijisu27**

### CODE REVIEW

**Comment by KhaosT** [comment]
Thx

**Comment by gekowa** [comment]
One important better part of tb3-enabler over the Thunderbolt3Unblocker is that, tb3-enabler works on the logon screen while the latter one doesn't, I believe this is the benefit of doing patch instead of introducing another kext.

We're luck that the `re_index[1]` still works on 10.14.5, it would be very nice if you could keep updating the patch in the future.

**Comment by hgyzqj** [comment]
could you approve this fix for 10.14.6.   tks

**Comment by hgyzqj** [comment]
could you approve this fix for 10.14.6

**Pull request merged**
