### PR TITLE
Update for 10.13.2

### PR DESCRIPTION
**Pull request by ahjsrhj**

### CODE REVIEW

**Comment by KhaosT** [comment]
Thanks, would you mind add the build number to version string?

**Comment by zb737472783** [comment]
Now this version is not available on 10.13? Estimate when to work properly?Thanks.

**Comment by KhaosT** [comment]
Thank you.

**Comment by ahjsrhj** [comment]
@KhaosT Ok, I added it.
@zb737472783 it works for 10.13.1

**Comment by ahjsrhj** [comment]
@zb737472783 now it works for all version

**Comment by ahjsrhj** [comment]
@KhaosT you are welcome😄

**Comment by zb737472783** [comment]
tb3-enabler.py <https://github.com/KhaosT/tb3-enabler/blob/master/tb3-enabler.py>  Can work on 10.13.1?

**Comment by ahjsrhj** [comment]
@zb737472783 Yes

**Pull request merged**
