### PR TITLE
Added 10.14 (18A391)

### PR DESCRIPTION
**Pull request by gekowa**
Tested on my machine.

image

### CODE REVIEW

**Comment by KhaosT** [comment]
Thanks :)

**Comment by Michaelkire** [comment]
Didn't work for me with a TB16 dock from Dell.

also I got this error
Kext with invalid signatured (-67054) allowed: <OSKext 0x7ff204949d80 [0x7fff8b1498e0]> { URL = "IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.iokit.IOThunderboltFamily" }

my mac is a MacBookPro15,1 running Mojave 10.14

**Comment by Zeke0n** [comment]
Also, not working on MacBook Pro 15 inch 2018 mojave.

**Review by oeegee — COMMENTED** [review]
Hello, good Job.
I have a question.
How to create string "07a13e6e367608846ecbe3a1154bd05c"?

Please note me~!
Thank you!

**Comment by Zeke0n** [comment]
@oeegee
md5 /System/Library/Extensions/IOThunderboltFamily.kext/Contents/MacOS/IOThunderboltFamily

**Comment by barongun** [comment]
I have 2018 new macbook pro with mojave, and the mac can recognize tb15. However, the tb15 can only charge, no usb and no video ouput.

**Comment by acschill** [comment]
Applied the updated patch. Semi-works. I have a 2016 Macbook Pro 13" and a Dell TB16 Thunderbolt dock. Ethernet connect is working fine through but displays do not work.

**Comment by Rayssadiel** [comment]
Hey,
is there a possibility to upgrade patch for the version macOS 10.14.1 (18B75)?

**Pull request merged**
