### PR TITLE
fix the 10.14.2 issue.

### PR DESCRIPTION
**Pull request by feijisu27**

### CODE REVIEW

**Review by KhaosT — COMMENTED** [review]
Can you uncomment b242fcabdf46bb83f083af2c97179bb2?

**Comment by feijisu27** [comment]
I have modify it, just test on the imac(2017 10.14.2)/mac min(2018 10.14.2), with the startech device.

**Comment by feijisu27** [comment]
could you merge this one?

**Comment by KhaosT** [comment]
👍

**Comment by oeegee** [comment]
Hello.
My system updated to 10.14.4 (18E226).
md5_version = {
"b1fc234210e63d9cc5a1f7c198418c01": ["10.14.4 (18E226)"]
}

How can I get md5_patch code?

**Comment by feijisu27** [comment]
you can issue a pull request if you have test the patch on 10.14.4, or I will try it when have time maybe this weekend.

**Comment by akinmusic** [comment]
md5_version=
672acec06dbd4bce4de36fbb0940a10a

> Hello.
> My system updated to 10.14.4 (18E226).
> md5_version = {
> "b1fc234210e63d9cc5a1f7c198418c01": ["10.14.4 (18E226)"]
> }
> 
> How can I get md5_patch code?

**Comment by acschill** [comment]
Hi there, how can I find the md5_version and md5_patch for 10.14.4 (18E227)? I'm a bit of a noob to all this so sorry for any ignorance on my part.

**Pull request merged**
