### PR TITLE
Add Mac OS 10.13.4 (17E199)

### PR DESCRIPTION
**Pull request by schwabe**

### CODE REVIEW

**Comment by majk4l** [comment]
Not working for me ( 10.13.4 17E199)

Dell Thunderbolt Dock - Unsupported:

  Vendor Name:	Dell
  Device Name:	Dell Thunderbolt Dock - Unsupported
  Vendor ID:	0xD4
  Device ID:	0xB054
  Device Revision:	0x1
  UID:	0x8086A321A5382310
  Route String:	301
  Firmware Version:	15,15

**Comment by victorzuo** [comment]
@majk4l Plug in first Dell Thunderbolt Dock, turn on the power

**Comment by victorzuo** [comment]
@schwabe You can use this installation https://github.com/rgov/Thunderbolt3Unblocker.

**Comment by majk4l** [comment]
I tried this link earlier but when I'm build the app in Xcode i get this errors : 
Code Signing Error: There are no accounts registered with Xcode. Add your developer account to Xcode
Code Signing Error: No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "G8YUUXXXXX" with a private key was found.
XXXXX - I deleted that string of numbers 

About your first adivce (Plug in first Dell Thunderbolt Dock, turn on the power), it's plugged all the time :)

**Comment by schwabe** [comment]
Works perfectly fine with my HP Thunderbolt Dock.

I took a brief look at the code posted by @victorzuo that looks good too (actually a bit better since it should not break on every kernel update) but for the moment I will stick to the patched kernel and maybe try the alternative approach on the next kernel update

**Comment by baobaobuku1210** [comment]
DisplayPort is no work，please help me！！

**Comment by relder001** [comment]
Not working for my TB16 on 10.13.4 either, I think perhaps likely due to broken support for DisplayLink in 10.13 by Apple (well discussed at www DisplayLink.  I did try loading latest beta version of DisplayLink Drivers, but that fails with 'unsupported' on the Thunderbolt Dock as well.

**Comment by KhaosT** [comment]
Thank you 🙏

**Comment by cacimbo** [comment]
unknown file, won't backup (md5=195a9eb4f4cbdbd479a48f8b79fab60f)


Any suggestion from anyone? Thanks

**Comment by ghost** [comment]
because security update (17E202) it seems that the kext file changed. i tried the manual edit and found/exchanged the string with worked for 17E199, but it didn't have any effect. still an Unsupported Atikio Node.

md5=e64e2678bb38f6f60d3a9647c5d53eb6 High Sierra 10.13.4 (17E202) Original
md5=555a6efce42709e06530251eb0f71315 patched with the 10.13.4 (17E199) string

EDIT: going back to the IOThunderboltFamily.kext from 17E199 works.

**Comment by schwabe** [comment]
I was curious but for me forceApply just worked fine with the 17202 and I have the same hash as you. I added the #20 pull request for it.

**Pull request merged**
